# Generated by Django 2.2.8 on 2020-02-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramchannel',
            name='last_update',
        ),
    ]
