# Generated by Django 2.2.8 on 2020-02-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_remove_telegramchannel_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannel',
            name='link',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='telegramchannelmessage',
            name='link',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='telegramchannelmessage',
            name='title',
            field=models.TextField(),
        ),
    ]
