# Generated by Django 2.2.8 on 2019-12-14 20:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('avatar', models.URLField(null=True)),
                ('curator_name', models.CharField(max_length=120)),
                ('curator_url', models.URLField(null=True)),
                ('curator_bio', models.CharField(max_length=120, null=True)),
                ('schema', models.TextField(null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('refreshed_at', models.DateTimeField()),
                ('frequency', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'boards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BoardFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(db_index=True)),
                ('refreshed_at', models.DateTimeField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='boards.Board')),
            ],
            options={
                'db_table': 'board_feeds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(db_index=True)),
                ('type', models.CharField(max_length=16)),
                ('domain', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('image', models.URLField(null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='boards.Board')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='boards.BoardFeed')),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
