# Generated by Django 2.2.8 on 2019-12-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='click_count',
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='boardfeed',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_index=True),
        ),
    ]
