# Generated by Django 2.2.8 on 2020-01-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_article_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='board',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
