# Generated by Django 2.2.8 on 2020-01-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200106_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['index', 'name']},
        ),
        migrations.AlterField(
            model_name='boardfeed',
            name='name',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
