# Generated by Django 2.2.8 on 2019-12-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20191214_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardfeed',
            old_name='url',
            new_name='rss_url',
        ),
        migrations.AddField(
            model_name='boardfeed',
            name='web_url',
            field=models.URLField(default='nope'),
            preserve_default=False,
        ),
    ]
