# Generated by Django 2.2.8 on 2019-12-14 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20191214_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardfeed',
            old_name='rss_url',
            new_name='rss',
        ),
        migrations.RenameField(
            model_name='boardfeed',
            old_name='web_url',
            new_name='url',
        ),
    ]
