# Generated by Django 2.2.8 on 2019-12-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20191214_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='frequency',
        ),
        migrations.AddField(
            model_name='boardfeed',
            name='frequency',
            field=models.FloatField(default=0.0),
        ),
    ]
