# Generated by Django 2.2.8 on 2019-12-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20191215_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardfeed',
            name='icon',
            field=models.URLField(null=True),
        ),
    ]
