# Generated by Django 2.2.8 on 2020-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20200122_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardfeed',
            name='is_parsable',
            field=models.BooleanField(default=True),
        ),
    ]
