# Generated by Django 2.2.13 on 2021-04-29 09:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20200905_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardfeed',
            name='filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
