# Generated by Django 2.2.13 on 2022-01-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_boardfeed_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardblock',
            name='is_publishing_to_telegram',
            field=models.BooleanField(default=False),
        ),
    ]
