# Generated by Django 2.2.8 on 2020-01-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20200104_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='board',
            name='avatar',
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='boardfeed',
            name='icon',
            field=models.URLField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='boardfeed',
            name='rss',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='boardfeed',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
