# Generated by Django 2.2.8 on 2020-01-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20200104_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='domain',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
