# Generated by Django 2.2.8 on 2020-01-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20200104_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='curator_title',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
