# Generated by Django 2.2.8 on 2020-01-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_board_curator_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='curator_footer',
            field=models.TextField(null=True),
        ),
    ]
