# Generated by Django 2.2.13 on 2022-01-22 14:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0011_boardblock_is_publishing_to_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=256)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_message_id', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published', to='boards.Article')),
            ],
            options={
                'db_table': 'publish_history',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardTelegramChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_channel_id', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_channel', to='boards.Board')),
            ],
            options={
                'verbose_name': "telegram channel to publish Board's updates",
                'db_table': 'board_telegram_channel',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='boardtelegramchannel',
            constraint=models.UniqueConstraint(fields=('board', 'telegram_channel_id'), name='unique_board_telegram_channel'),
        ),
    ]
