# Generated by Django 2.2.13 on 2022-01-16 14:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0010_boardfeed_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=256)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent', to='boards.Article')),
            ],
            options={
                'db_table': 'sent_history',
                'ordering': ['-sent_at'],
            },
        ),
    ]
