# Generated by Django 2.2.13 on 2022-01-18 03:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_boardfeed_filters'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=256)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_message_id', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published', to='boards.Article')),
            ],
            options={
                'db_table': 'publish_history',
                'ordering': ['-published_at'],
            },
        ),
        migrations.DeleteModel(
            name='SentHistory',
        ),
    ]
