# Generated by Django 2.2.13 on 2022-01-18 03:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_boardfeed_filters'),
        ('notifications', '0002_auto_20220118_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTelegramChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_channel', to='boards.Board')),
            ],
            options={
                'db_table': 'board_telegram_channel',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='boardtelegramchannel',
            constraint=models.UniqueConstraint(fields=('board', 'channel_id'), name='unique_board_telegram_channel'),
        ),
    ]
